# Generated by Django 2.1.5 on 2019-06-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'managed': False, 'verbose_name_plural': 'banks'},
        ),
        migrations.AlterModelOptions(
            name='branches',
            options={'managed': False, 'verbose_name_plural': 'branches'},
        ),
    ]
